# Generated by Django 4.1.9 on 2023-05-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='image',
            field=models.CharField(default='https://www.equalityhumanrights.com/sites/default/files/styles/listing_image/public/default_images/blog-teaser-default-full_5.jpg?itok=YOsTg-7X', max_length=50),
            preserve_default=False,
        ),
    ]
